export const metadata = {
  title: 'Jasai Art',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es-MX">
      <link rel="shortcut icon" href="https://web.opendrive.com/api/v1/download/file.json/NDFfNTQ4MDY1ODRfY01td1c?session_id=3a6238c3dbf44f2a48119e3c31ba8269b53173d247cfbb6ee6b84a8592cb6c16&inline=1&preview=1" />
      <body>{children}</body>
    </html>
  )
}
